version: '3.4'

services:
  consoleapp:
    image: ${DOCKER_REGISTRY-}consoleapp
    build:
      context: .
      dockerfile: ConsoleApp/Dockerfile
  mssql:
    image: "microsoft/mssql-server-linux:latest"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "myStrong!PassWord"
    ports:
      - '1433:1433'
    volumes:
      - csharpdemos-data:/var/opt/mssql/data

volumes:
  csharpdemos-data:
